fmdd_sylius_marketing_admin_cart_abandoned:
    resource: |
        alias: fmdd_sylius_marketing.cart_abandoned
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: fmdd_sylius_marketing_cart_abandoned
        vars:
            all:
                subheader: fmdd_sylius_marketing.ui.cart_abandoneds
                templates:
                    form: '@FMDDSyliusMarketingPlugin/CartAbandoned/_form.html.twig'
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: admin

fmdd_sylius_marketing_admin_notification:
    resource: |
        alias: fmdd_sylius_marketing.notification
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: fmdd_sylius_marketing_notification
        vars:
            all:
                subheader: fmdd_sylius_marketing.ui.notifications
                templates:
                    form: '@FMDDSyliusMarketingPlugin/Notification/_form.html.twig'
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: admin

fmdd_sylius_marketing_admin_notification_type:
    resource: |
        alias: fmdd_sylius_marketing.notification_type
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: fmdd_sylius_marketing_notification_type
        vars:
            all:
                subheader: fmdd_sylius_marketing.ui.notification_types
                templates:
                    form: '@FMDDSyliusMarketingPlugin/Notification/_form.html.twig'
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: admin
