sylius_resource:
    resources:
        fmdd_sylius_marketing.notification_type:
            driver: doctrine/orm
            classes:
                model: FMDD\SyliusMarketingPlugin\Entity\NotificationType
                form: FMDD\SyliusMarketingPlugin\Form\NotificationTypeType

sylius_grid:
    grids:
        fmdd_sylius_marketing_notification_type:
            driver:
                name: doctrine/orm
                options:
                    class: FMDD\SyliusMarketingPlugin\Entity\NotificationType
                    form: FMDD\SyliusMarketingPlugin\Form\NotificationTypeType
            fields:
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: true
                    options:
                        template: SyliusUiBundle:Grid/Field:enabled.html.twig
                code:
                    type: string
                    label: "Code"
                    sortable: true
                name:
                    type: string
                    label: "Name"
                    sortable: true
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, name]
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
