sylius_resource:
    resources:
        fmdd_sylius_marketing.cart_abandoned:
            driver: doctrine/orm
            classes:
                model: FMDD\SyliusMarketingPlugin\Entity\CartAbandoned
                form: FMDD\SyliusMarketingPlugin\Form\CartAbandonedType

sylius_grid:
    grids:
        fmdd_sylius_marketing_cart_abandoned:
            driver:
                name: doctrine/orm
                options:
                    class: FMDD\SyliusMarketingPlugin\Entity\CartAbandoned
                    form: FMDD\SyliusMarketingPlugin\Form\CartAbandonedType
            fields:
                status:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: true
                    options:
                        template: SyliusUiBundle:Grid/Field:enabled.html.twig
                subject:
                    type: string
                    label: "Subject"
                    sortable: true
                template:
                    type: string
                    label: "Template"
                    sortable: true
                sendDelay:
                    type: string
                    label: "Send after (mins)"
                    sortable: true
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [subject, template]
                status:
                    type: boolean
                    label: sylius.ui.enabled
