services:
  fmdd.event.listener.jsonld:
    parent: "fmdd.event.listener.marketing.abstract"
    class: FMDD\SyliusMarketingPlugin\EventListener\JsonldListener
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.jsonld.website, method: buildWebsite}
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.jsonld.product, method: buildProduct}
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.jsonld.contact.business, method: buildContactBusiness}
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.jsonld.local.business, method: buildLocalBusiness}
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.jsonld.breadcrumb.product, method: buildBreadcrumbProduct}
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.jsonld.breadcrumb.search, method: buildBreadcrumbSearch}
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.jsonld.breadcrumb.taxon, method: buildBreadcrumbTaxon}
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.jsonld.faq, method: buildFaq}
