services:
  fmdd.listener.admin.menu_builder:
    class: FMDD\SyliusMarketingPlugin\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  fmdd.command.cart_abandoned:
    class: FMDD\SyliusMarketingPlugin\Command\CartAbandonedCommand
    tags:
      - { name: console.command, command: 'fmdd:cart-abandoned:run'}
    arguments:
      - '@doctrine'
      - '@sylius.email_sender'
      - '@parameter_bag'
      - '@sylius.repository.order'
      - '@fmdd_sylius_marketing.repository.cart_abandoned'
      - '@fmdd_sylius_marketing.repository.cart_abandoned_send'

  fmdd.command.notification_order_load:
    class: FMDD\SyliusMarketingPlugin\Command\NotificationOrderLoadCommand
    tags:
      - { name: console.command, command: 'fmdd:notification-order:load'}
    arguments:
      - '@sylius.repository.order'
      - '@fmdd.event.listener.notification_order_payed'
      - '@doctrine'
