services:
  fmdd.listener.admin.menu_builder:
    class: FMDD\SyliusMarketingPlugin\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  fmdd_sylius_marketing.repository.cart_abandonned_send:
    class: FMDD\SyliusMarketingPlugin\Repository\CartAbandonedSendRepository
    autowire: true

  fmdd.command.cart_abandoned:
    class: FMDD\SyliusMarketingPlugin\Command\CartAbandonedCommand
    tags:
      - { name: console.command, command: 'fmdd:cart-abandoned:run'}
    arguments:
      - '@fmdd_sylius_marketing.repository.cart_abandoned'
      - '@fmdd_sylius_marketing.repository.cart_abandonned_send'
      - '@sylius.repository.order'
      - '@doctrine.orm.entity_manager'
      - '@sylius.email_sender'
      - '@parameter_bag'
