fmdd_sylius_marketing_admin:
  resource: routing/admin.yml
  prefix: /admin

setono_sylius_trustpilot_admin:
  resource: "@SetonoSyliusTrustpilotPlugin/Resources/config/admin_routing.yaml"
  prefix: /admin
