imports:
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/commands.yml" }
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/controller.yml" }
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/grids.yml" }
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/listener.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/mailer.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/services.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/winzou.yml" }
  - { resource: "@SetonoSyliusTrustpilotPlugin/Resources/config/app/config.yaml" }

parameters:
  fmdd_instagram_url_tag: 'your_instagram_profile_url_tag'
