imports:
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/commands.yml" }
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/controller.yml" }
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/grids.yml" }
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/listener.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/mailer.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/services.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/package/winzou.yml" }
  - { resource: "@SetonoSyliusTrustpilotPlugin/Resources/config/app/config.yaml" }

twig:
  globals:
    instagram_provider: '@fmdd.instagram.oembed.provider'
