imports:
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/services.yml" }
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/winzou.yml" }
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/grids.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/mailer.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/services.yml" }
  - { resource: "@SetonoSyliusTrustpilotPlugin/Resources/config/app/config.yaml" }
