fmdd_sylius_marketing_admin:
  resource: "@FMDDSyliusMarketingPlugin/Resources/config/routing/admin.yml"
  prefix: '/%sylius_admin.path_name%'

fmdd_sylius_marketing_grids:
  resource: "@FMDDSyliusMarketingPlugin/Resources/config/routing/grids.yml"

fmdd_sylius_marketing_shop:
  resource: "@FMDDSyliusMarketingPlugin/Resources/config/routing/shop.yml"
