imports:
  - { resource: "./service/listener/marketing.yml"}
  - { resource: "./service/listener/jsonld.yml"}
  - { resource: "./service/commands.yml"}

services:
  FMDD\SyliusMarketingPlugin\:
    resource: '../../*'
    exclude: '../../{Entity,Migrations,FMDDSyliusMarketingPlugin.php}'

  fmdd.form.channel_type.extension:
    class: FMDD\SyliusMarketingPlugin\Form\Extension\ChannelTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ChannelBundle\Form\Type\ChannelType }
      
  setono_sylius_trustpilot.email_manager:
    class: FMDD\SyliusMarketingPlugin\Trustpilot\EmailManager
    arguments: ['@sylius.email_sender', '%setono_sylius_trustpilot.trustpilot_email%', '%locale%']
