parameters:
  google.analytics: "GA-"
  google.conversion: "AW-"
  google.event.checkout.progress: ""
  facebook.pixel: ""
  url.privacy: ""
  website.name: ""
  author: ""
  contact.email: ""

services:
  fmdd.event.listener.marketing:
    class: FMDD\SyliusMarketingPlugin\EventListener\MarketingListener
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.head, method: buildLayoutHeader }
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.checkout.complete.after_steps, method: buildAddPaymentInfo }
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.index.after_box, method: buildBoxProduct }
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.checkout.address.after_steps, method: buildCheckoutBegin }
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.order.thank_you.after_message, method: buildPurchase }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.checkout_progress, method: buildCheckoutProgress }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.exception, method: buildException }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.metadata, method: buildMetadata }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.product_index, method: buildProductIndex }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.product_show, method: buildProductShow }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.promotion, method: buildPromotion }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.registration, method: buildRegistration }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.search, method: buildSearch }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.selectPayment, method: buildSelectPayment }
      - { name: kernel.event_listener, event: sonata.block.event.fmdd.event.marketing.view_item_list, method: buildViewItemList }
