imports:
    - { resource: "./service/listener/marketing.yml"}
    - { resource: "./service/listener/jsonld.yml"}
    - { resource: "./service/commands.yml"}

services:
    FMDD\SyliusMarketingPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,FMDDSyliusMarketingPlugin.php}'
