twig:
  globals:
    google_analytics: "%google.analytics%"
    google_conversion: "%google.conversion%"
    google_event_purchase: "%google.event.purchase%"
    google_event_search: "%google.event.search%"
    google_event_product_show: "%google.event.product_show%"
    google_event_registration: "%google.event.registration%"
    google_event_checkout_progress: "%google.event.checkout.progress%"
    google_event_select_payment: "%google.event.select.payment%"
    facebook_pixel: "%facebook.pixel%"
    url_privacy: "%url.privacy%"
    website_name: "%website.name%"
    author: "%author%"
    contact_email: "%contact.email%"
