twig:
  globals:
    google_analytics: "%google.analytics%"
    google_adwords: "%google.adwords%"
    google_id: "%google.id%"
    google_type_merchant: "%google.type.merchant%"
    google_event_purchase: "%google.event.purchase%"
    google_event_search: "%google.event.search%"
    google_event_product_show: "%google.event.product_show%"
    google_event_registration: "%google.event.registration%"
    google_event_checkout_progress: "%google.event.checkout.progress%"
    google_event_select_payment: "%google.event.select.payment%"
    contact_geo_opening_hours: "%contact_geo_opening_hours%"
    contact_geo_latitude_longitude: "%contact_geo_latitude_longitude%"
    facebook_pixel: "%facebook.pixel%"
    url_privacy: "%url.privacy%"
    website_name: "%website.name%"
    author: "%author%"
