twig:
  globals:
    google_analytics: "%google.analytics%"
    facebook_pixel: "%facebook.pixel%"
    url_privacy: "%url.privacy%"
    website_name: "%website.name%"
    author: "%author%"
    contact_email: "%contact.email%"
