services:
  fmdd.instagram.controller:
    class: FMDD\SyliusMarketingPlugin\Controller\InstagramController
    arguments:
      - '@fmdd.instagram.oembed.provider'
      - '@fmdd_sylius_marketing.repository.instagram_post'
    public: true

  fmdd.notification.controller:
    class: FMDD\SyliusMarketingPlugin\Controller\NotificationController
    arguments: ['@doctrine', '@time.datetime_formatter', '@templating.engine.twig']
    public: true

  fmdd.product.controller:
    class: FMDD\SyliusMarketingPlugin\Controller\ProductController
    arguments: ['@sylius.repository.product']
    public: true
