imports:
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/grids/fmdd_sylius_marketing_instagram_post.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/grids/fmdd_sylius_marketing_cart_abandoned.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/grids/fmdd_sylius_marketing_notification.yml"}
  - { resource: "@FMDDSyliusMarketingPlugin/Resources/config/grids/fmdd_sylius_marketing_notification_type.yml"}
