sylius_mailer:
    emails:
        no_payment:
            template: "@FMDDSyliusMarketingPlugin/CartAbandoned/Emails/no_payment.html.twig"
        no_checkout:
            template: "@FMDDSyliusMarketingPlugin/CartAbandoned/Emails/no_checkout.html.twig"
