sylius_ui:
  events:
    fmdd.marketing.shop.layout.notification:
      blocks:
        notification.css: '@@FMDDSyliusMarketingPlugin/Notification/Block/_style.html.twig'
        notification.js: '@@FMDDSyliusMarketingPlugin/Notification/Block/_javascript.html.twig'
