sylius_ui:
  events:
    fmdd.marketing.shop.layout.notification:
      blocks:
        notification.css:
          template: '@FMDDSyliusMarketingPlugin/Notification/Block/_style.html.twig'
        notification.js:
          template: '@FMDDSyliusMarketingPlugin/Notification/Block/_javascript.html.twig'
